docs_dir: docs
site_name: Robotický tábor 2025
site_url: https://2025.robotickytabor.cz/
site_description: >-
  Robotický tábor 2025

repo_name: RoboticsBrno/RoboCamp-2025
repo_url: https://github.com/RoboticsBrno/RoboCamp-2025
# edit_uri: blob/main/docs/

dev_addr: "127.0.0.1:8000"
copyright: Copyright © RoboticsBrno
use_directory_urls: True

theme:
  name: material
  language: cs
  logo: assets/logo.svg
  favicon: assets/logo.svg
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - content.code.annotate
  custom_dir: overrides

  icon:
    repo: fontawesome/brands/github

  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Přepnout na světý režim
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Přepnout na tmavý režim

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.keys
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - attr_list
  - pymdownx.tabbed
  - meta
  - pymdownx.snippets:
      url_download: True
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: "¤"
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - open-in-new-tab
  - glightbox:
      auto_caption: true
  - resize-images:
      source-dir: assets-large
      target-dir: assets
      enable_cache: True
      size: [1000, 800]
      extensions: [".jpg", ".jpeg", ".png", ".gif"]
  # - typedoc:
  #     source: "./docs/elks/lekce1/example1/@types/*.d.ts"
  #     output_dir: "jaculusApi"
  #     tsconfig: "./docs/elks/lekce1/example1/tsconfig.json"
  #     options: "typedoc.json"
  #     name: "Jaculus API documentation"

  # - zip_folders:
  #     folders:
  #       - robot/lekce1/example1
  #       - robot/lekce3/project3
  #       - robot/lekce4/project4
  #       - robot/lekce6/project6
  #       - robot/lekce8/project8
  #     debug: true

  - auto-refresh-build-pages:
      update_message: "Návod byl aktualizován, chcete načíst novou verzi?"
      yes_button_text: "Ano"
      no_button_text: "Ne"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/RoboticsBrno
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/RobotikaBrno
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/robotarna.helceletka
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@robotikabrno-robotarnaasps2392
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/robotarna.helceletka

extra_css:
  - assets/style.css

nav:
  - Domů:
      - index.md
  - Robůtek:
      - https://robutek.robotikabrno.cz/v1/
  - Gadgets:
      - https://gadgets.robotikabrno.cz/
  - Náš tým:
      - https://robotikabrno.cz/cs/nas-tym/
